In [6]:
import numpy as np

In [7]:
np.array([5,5])

array([5, 5])

In [8]:
np.zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [13]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [15]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [17]:
arr/2

array([[0, 1, 1, 2],
       [2, 3, 3, 4]])

In [19]:
from __future__ import division

In [20]:
arr/2

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ]])

In [21]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])